name: Tests
on: [push, pull_request]

jobs:
    test:
        name: Tests
        strategy:
            matrix:
                os: [ubuntu-18.04, ubuntu-20.04]
                dc: [dmd-latest, ldc-latest, dmd-beta, ldc-beta]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2

            - name: Install D compiler
              uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ${{ matrix.dc }}

            - name: Run tests
              run: make test DC=$DC
